---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operators
  labels:
    istio-injection: disabled
